# ****************
# SESSIONS (Sessões)
# ****************
### 1. Autenticação (login Admin)
POST http://localhost:3333/sessions HTTP/1.1
content-type: application/json

{
    "email": "admin@email.com",
    "password": "123abc"
}

### 1. Autenticação (login Member)
POST http://localhost:3333/sessions HTTP/1.1
content-type: application/json

{
    "email": "joao@email.com",
    "password": "123abc"
}
